name: ISeeYou
version: ${version}
main: cn.xor7.iseeyou.ISeeYou
api-version: '1.20', '1.21'
dependencies:
  server:
    Themis:
      load: BEFORE
      required: false
    Matrix:
      load: BEFORE
      required: false
    Vulcan:
      load: BEFORE
      required: false
    Negativity:
      load: BEFORE
      required: false
    GrimAC:
      load: BEFORE
      required: false
    LightAntiCheat:
      load: BEFORE
      required: false
    Spartan:
      load: BEFORE
      required: false